# Generated by Django 6.0.6 on 2026-06-29 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0002_bloodrequest_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='created_at',
        ),
    ]
